version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.6
      # python: 3.8  # Uncomment if you need Python for Lambda or scripting
    commands:
      - echo Installing Terraform dependencies
      # - pip install --upgrade pip          # Uncomment if Python is used
      # - pip install awscli terraform       # Uncomment if you're installing via pip (not needed for CodeBuild image)

  pre_build:
    commands:
      - echo Logging in to AWS
      - aws sts get-caller-identity
      - export AWS_REGION=ap-south-1

  build:
    commands:
      - echo Initializing Terraform
      - terraform init
      - echo Running Terraform plan
      - terraform plan

  post_build:
    commands:
      - echo Applying Terraform
      - terraform apply -auto-approve

artifacts:
  files:
    - '**/*'
